upstream rate-limiting {
    server rate-limiting-server-instance-1:8080;
    server rate-limiting-server-instance-2:8080;
}

server {
    listen 80;

    location / {
        proxy_pass http://rate-limiting;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
